name: Update a file with the new Kubernetes version

on:
  workflow_call:
    inputs:
      repository:
        description: "Repository to update format: owner/repo"
        required: true
        type: string
      branch:
        description: "Branch to update e.g. main, master, dev"
        required: true
        default: main
        type: string
      file:
        description: "Path to the file to update eg. ./k8s/deployment.yaml"
        required: true
        type: string
      version:
        description: "New version to update the file with"
        required: true
        type: string
      image:
        description: "Image name to update the file with"
        required: true
        type: string
    secrets:
      PRIVATE_REPO_KEY:
        description: "Private repository key"
        required: true

env:
  REGISTRY: ghcr.io

jobs:
  image:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ inputs.image }}
      VERSION: ${{ inputs.version }}
      FILE: ${{ inputs.file }}
      BRANCH: ${{ inputs.branch }}
    permissions:
      contents: write

    steps:
      - name: Debug repository info
        run: |
          echo "Repository: ${{ inputs.repository }}"
          echo "Branch: ${{ inputs.branch }}"
          echo "Token: ${{ secrets.PRIVATE_REPO_KEY }}"
          git ls-remote https://github.com/${{ inputs.repository }}.git

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.branch }}
          token: ${{ secrets.PRIVATE_REPO_KEY }}

      - name: Update Kubernetes deployment file
        run: |
          sed -i "s|${REGISTRY}/${IMAGE_NAME}:[^\"]*|${REGISTRY}/${IMAGE_NAME}:${VERSION}|" ${FILE}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ${FILE}
          git commit -m "Update deployment image version to ${VERSION} [skip ci]"
          git push origin HEAD:${BRANCH}
